// // export const OPEN_CONTAINER_MODAL = "OPEN_CONTAINER_MODAL";
// // export const CLOSE_CONTAINER_MODAL = "CLOSE_CONTAINER_MODAL";

// // export const CREATE_CONTAINER_REQUEST = "CREATE_CONTAINER_REQUEST";
// // export const CREATE_CONTAINER_SUCCESS = "CREATE_CONTAINER_SUCCESS";
// // export const CREATE_CONTAINER_FAILURE = "CREATE_CONTAINER_FAILURE";

// // // Optional: for fetching dropdowns (container groups / ports)
// // export const FETCH_CONTAINER_GROUPS_REQUEST = "FETCH_CONTAINER_GROUPS_REQUEST";
// // export const FETCH_CONTAINER_GROUPS_SUCCESS = "FETCH_CONTAINER_GROUPS_SUCCESS";
// // export const FETCH_CONTAINER_GROUPS_FAILURE = "FETCH_CONTAINER_GROUPS_FAILURE";

// // export const FETCH_PORTS_REQUEST = "FETCH_PORTS_REQUEST";
// // export const FETCH_PORTS_SUCCESS = "FETCH_PORTS_SUCCESS";
// // export const FETCH_PORTS_FAILURE = "FETCH_PORTS_FAILURE";

// export const CREATE_CONTAINER_REQUEST = "CREATE_CONTAINER_REQUEST";
// export const CREATE_CONTAINER_SUCCESS = "CREATE_CONTAINER_SUCCESS";
// export const CREATE_CONTAINER_FAILURE = "CREATE_CONTAINER_FAILURE";
