export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const OTP_SENT = "OTP_SENT";
export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";

export const OTP_RESEND_REQUEST = "OTP_RESEND_REQUEST";
export const OTP_RESEND_SUCCESS = "OTP_RESEND_SUCCESS";
export const OTP_RESEND_FAILURE = "OTP_RESEND_FAILURE";

export const CLOSE_OTP_MODAL = "CLOSE_OTP_MODAL";
