
export const FETCH_CONTAINERS_REQUEST = "FETCH_CONTAINERS_REQUEST";
export const FETCH_CONTAINERS_SUCCESS = "FETCH_CONTAINERS_SUCCESS";
export const FETCH_CONTAINERS_FAILURE = "FETCH_CONTAINERS_FAILURE";

// export const DELETE_CONTAINER_REQUEST = "DELETE_CONTAINER_REQUEST";
// export const DELETE_CONTAINER_SUCCESS = "DELETE_CONTAINER_SUCCESS";
// export const DELETE_CONTAINER_FAILURE = "DELETE_CONTAINER_FAILURE";

// Create
// export const CREATE_CONTAINER_REQUEST = "CREATE_CONTAINER_REQUEST";
// export const CREATE_CONTAINER_SUCCESS = "CREATE_CONTAINER_SUCCESS";
// export const CREATE_CONTAINER_FAILURE = "CREATE_CONTAINER_FAILURE";

// View
export const VIEw_CONTAINER_REQUEST = "VIEW_CONTAINER_REQUEST";
export const VIEW_CONTAINER_SUCCESS = "VIEW_CONTAINER_SUCCESS";
export const VIEW_CONTAINER_FAILURE = "VIEW_CONTAINER_FAILURE";

// Edit (PUT)
export const EDIT_CONTAINER_REQUEST = "EDIT_CONTAINER_REQUEST";
export const EDIT_CONTAINER_SUCCESS = "EDIT_CONTAINER_SUCCESS";
export const EDIT_CONTAINER_FAILURE = "EDIT_CONTAINER_FAILURE";
